#!/usr/bin/env bash

set -euo pipefail

# ============================================================
# Variant concordance stratified by variant type
# ============================================================
#
# Calculates concordance separately for SNPs and indels using
# the normalized VCFs and bcftools isec outputs generated by:
#
#   06_variant_concordance.sh
#
# For each sample and variant type, the script calculates:
#
#   - Local variants
#   - External variants
#   - Shared variants
#   - Local-only variants
#   - External-only variants
#   - Local shared percentage
#   - External shared percentage
#   - Jaccard index
#
# Requirements:
#   - BCFtools
#
# Usage:
#
#   bash scripts/07_concordance_by_type.sh \
#       /path/to/concordance_directory
#
# The input directory must contain:
#
#   local_normalized/
#   external_normalized/
#   isec/
#
# ============================================================


# ------------------------------------------------------------
# 1. Argument
# ------------------------------------------------------------

CONCORDANCE_DIR="${1:-}"

if [[ -z "$CONCORDANCE_DIR" ]]; then
    echo "Usage:"
    echo "  bash scripts/07_concordance_by_type.sh <concordance_directory>"
    exit 1
fi


# ------------------------------------------------------------
# 2. Check inputs and dependency
# ------------------------------------------------------------

LOCAL_DIR="$CONCORDANCE_DIR/local_normalized"
EXTERNAL_DIR="$CONCORDANCE_DIR/external_normalized"
ISEC_DIR="$CONCORDANCE_DIR/isec"

if [[ ! -d "$LOCAL_DIR" || \
      ! -d "$EXTERNAL_DIR" || \
      ! -d "$ISEC_DIR" ]]; then

    echo "ERROR: Expected concordance directories were not found."
    echo
    echo "Required:"
    echo "  $LOCAL_DIR"
    echo "  $EXTERNAL_DIR"
    echo "  $ISEC_DIR"
    exit 1
fi

if ! command -v bcftools >/dev/null 2>&1; then
    echo "ERROR: BCFtools was not found in PATH."
    exit 1
fi


# ------------------------------------------------------------
# 3. Output file
# ------------------------------------------------------------

OUTPUT="$CONCORDANCE_DIR/concordance_by_type.tsv"

printf "Sample\tType\tLocal\tExternal\tShared\tOnly_local\tOnly_external\tLocal_shared_percent\tExternal_shared_percent\tJaccard_percent\n" \
    > "$OUTPUT"


# ------------------------------------------------------------
# 4. Find normalized local VCFs
# ------------------------------------------------------------

mapfile -t LOCAL_VCFS < <(
    find "$LOCAL_DIR" \
        -maxdepth 1 \
        -type f \
        -name "*.vcf.gz" \
        ! -name "*.full.vcf.gz" \
        | sort
)

if [[ ${#LOCAL_VCFS[@]} -eq 0 ]]; then
    echo "ERROR: No normalized local VCFs were found."
    exit 1
fi


# ------------------------------------------------------------
# 5. Process each sample
# ------------------------------------------------------------

for LOCAL_VCF in "${LOCAL_VCFS[@]}"; do

    filename=$(basename "$LOCAL_VCF")
    SAMPLE="${filename%.vcf.gz}"

    EXTERNAL_VCF="$EXTERNAL_DIR/${SAMPLE}.vcf.gz"
    SAMPLE_ISEC="$ISEC_DIR/${SAMPLE}"

    echo "Processing: $SAMPLE"

    if [[ ! -f "$EXTERNAL_VCF" ]]; then
        echo "ERROR: External normalized VCF not found for $SAMPLE"
        exit 1
    fi

    if [[ ! -d "$SAMPLE_ISEC" ]]; then
        echo "ERROR: isec directory not found for $SAMPLE"
        exit 1
    fi


    # --------------------------------------------------------
    # Analyze SNPs and indels separately
    # --------------------------------------------------------

    for TYPE in snps indels; do

        if [[ "$TYPE" == "snps" ]]; then
            LABEL="SNP"
        else
            LABEL="INDEL"
        fi


        # ----------------------------------------------------
        # Total variants by type
        # ----------------------------------------------------

        LOCAL_N=$(
            bcftools view -v "$TYPE" -H "$LOCAL_VCF" |
            wc -l |
            tr -d ' '
        )

        EXTERNAL_N=$(
            bcftools view -v "$TYPE" -H "$EXTERNAL_VCF" |
            wc -l |
            tr -d ' '
        )


        # ----------------------------------------------------
        # Shared and exclusive variants
        # ----------------------------------------------------

        ONLY_LOCAL=$(
            bcftools view \
                -v "$TYPE" \
                -H "$SAMPLE_ISEC/0000.vcf" |
            wc -l |
            tr -d ' '
        )

        ONLY_EXTERNAL=$(
            bcftools view \
                -v "$TYPE" \
                -H "$SAMPLE_ISEC/0001.vcf" |
            wc -l |
            tr -d ' '
        )

        SHARED=$(
            bcftools view \
                -v "$TYPE" \
                -H "$SAMPLE_ISEC/0002.vcf" |
            wc -l |
            tr -d ' '
        )


        # ----------------------------------------------------
        # Percentages
        # ----------------------------------------------------

        LOCAL_SHARED_PERCENT=$(
            awk -v c="$SHARED" -v n="$LOCAL_N" '
                BEGIN {
                    if (n > 0)
                        printf "%.2f", (c/n)*100
                    else
                        printf "0.00"
                }
            '
        )

        EXTERNAL_SHARED_PERCENT=$(
            awk -v c="$SHARED" -v n="$EXTERNAL_N" '
                BEGIN {
                    if (n > 0)
                        printf "%.2f", (c/n)*100
                    else
                        printf "0.00"
                }
            '
        )

        JACCARD=$(
            awk \
                -v c="$SHARED" \
                -v ol="$ONLY_LOCAL" \
                -v oe="$ONLY_EXTERNAL" '
                BEGIN {
                    union = c + ol + oe

                    if (union > 0)
                        printf "%.2f", (c/union)*100
                    else
                        printf "0.00"
                }
            '
        )


        # ----------------------------------------------------
        # Write result
        # ----------------------------------------------------

        printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n" \
            "$SAMPLE" \
            "$LABEL" \
            "$LOCAL_N" \
            "$EXTERNAL_N" \
            "$SHARED" \
            "$ONLY_LOCAL" \
            "$ONLY_EXTERNAL" \
            "$LOCAL_SHARED_PERCENT" \
            "$EXTERNAL_SHARED_PERCENT" \
            "$JACCARD" \
            >> "$OUTPUT"

    done

done


# ------------------------------------------------------------
# 6. Calculate global results by variant type
# ------------------------------------------------------------

for LABEL in SNP INDEL; do

    GLOBAL_LOCAL=$(
        awk -F'\t' -v type="$LABEL" '
            NR > 1 && $2 == type {sum += $3}
            END {print sum+0}
        ' "$OUTPUT"
    )

    GLOBAL_EXTERNAL=$(
        awk -F'\t' -v type="$LABEL" '
            NR > 1 && $2 == type {sum += $4}
            END {print sum+0}
        ' "$OUTPUT"
    )

    GLOBAL_SHARED=$(
        awk -F'\t' -v type="$LABEL" '
            NR > 1 && $2 == type {sum += $5}
            END {print sum+0}
        ' "$OUTPUT"
    )

    GLOBAL_ONLY_LOCAL=$(
        awk -F'\t' -v type="$LABEL" '
            NR > 1 && $2 == type {sum += $6}
            END {print sum+0}
        ' "$OUTPUT"
    )

    GLOBAL_ONLY_EXTERNAL=$(
        awk -F'\t' -v type="$LABEL" '
            NR > 1 && $2 == type {sum += $7}
            END {print sum+0}
        ' "$OUTPUT"
    )

    LOCAL_PERCENT=$(
        awk -v c="$GLOBAL_SHARED" -v n="$GLOBAL_LOCAL" '
            BEGIN {
                if (n > 0)
                    printf "%.2f", (c/n)*100
                else
                    printf "0.00"
            }
        '
    )

    EXTERNAL_PERCENT=$(
        awk -v c="$GLOBAL_SHARED" -v n="$GLOBAL_EXTERNAL" '
            BEGIN {
                if (n > 0)
                    printf "%.2f", (c/n)*100
                else
                    printf "0.00"
            }
        '
    )

    JACCARD=$(
        awk \
            -v c="$GLOBAL_SHARED" \
            -v ol="$GLOBAL_ONLY_LOCAL" \
            -v oe="$GLOBAL_ONLY_EXTERNAL" '
            BEGIN {
                union = c + ol + oe

                if (union > 0)
                    printf "%.2f", (c/union)*100
                else
                    printf "0.00"
            }
        '
    )

    printf "Global\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n" \
        "$LABEL" \
        "$GLOBAL_LOCAL" \
        "$GLOBAL_EXTERNAL" \
        "$GLOBAL_SHARED" \
        "$GLOBAL_ONLY_LOCAL" \
        "$GLOBAL_ONLY_EXTERNAL" \
        "$LOCAL_PERCENT" \
        "$EXTERNAL_PERCENT" \
        "$JACCARD" \
        >> "$OUTPUT"

done


# ------------------------------------------------------------
# 7. Final report
# ------------------------------------------------------------

echo
echo "============================================================"
echo "Concordance by variant type completed"
echo "============================================================"

grep '^Global' "$OUTPUT"

echo
echo "Output:"
echo "  $OUTPUT"
echo "============================================================"
